$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train_track_analyzer_asli
display_name: train_track_analyzer

type: command
inputs:
  input_data: 
    type: uri_folder
  
outputs:
  output_data:
    type: uri_folder
    path: azureml://datastores/input_data/paths/output/${{name}}
code: ./train_src
environment: azureml:track-analysis-env:2
command: >-
  python train.py 
  --input_data ${{inputs.input_data}} 
  --output_data ${{outputs.output_data}}